### ISSUE TITLE
Can you provide the dataset preparation and the download links?

### ISSUE THREAD

**Issue by yahooo-m** [henghuiding/ReLA#1]

**Comment by henghuiding** [comment]
Thank you for your attention. For dataset download, please refer to [here](https://github.com/henghuiding/gRefCOCO), we will update the document for more detailed preparation within one week.

**Comment by yahooo-m** [comment]
Thanks! 
This is really a great job!

**Comment by yahooo-m** [comment]
Could you please show me the directory structure of the datasets folder?

**Comment by ntuLC** [comment]
A basic structure of the folder `datasets` would be like this:

```
datasets
├── grefcoco
│   ├── grefs(unc).json
│   ├── instances.json
├── images
│   └── train2014
├── refcoco
│   ├── instances.json
│   ├── refs(google).p
│   └── refs(unc).p
├── refcoco+
│   ├── instances.json
│   └── refs(unc).p
└── refcocog
    ├── instances.json
    ├── refs(google).p
    └── refs(umd).p
```

We will be updating the detailed documentation and making the code easier to use in the next few days. Please stay tuned!

**Comment by yahooo-m** [comment]
Thanks!

**Comment by yahooo-m** [comment]
Thanks! The code is clear.

**Comment by Seonghoon-Yu** [comment]
Thanks for releasing the code and pre-trained weights.

**Comment by ntuLC** [comment]
Documents and code are updated.
