### ISSUE TITLE
Question on evaluation result

### ISSUE THREAD

**Issue by lizhyuxi** [henghuiding/ReLA#10]
I performe the given Inference code but get the different evaluation result from that in the paper: 
My gIoU is 66.3407, cIoU is 63.0991, but in the paper they are respectively 63.60 and 62.42

Here follow my running code, file directory and the output. Is there anything wrong? Thank you.

!python train_net.py \
    --config-file configs/referring_swin_base.yaml \
    --num-gpus 1 --dist-url auto --eval-only \
    MODEL.WEIGHTS "/content/ReLA/gres_swin_base.pth" \
    OUTPUT_DIR "/content/ReLA"
![image](https://github.com/henghuiding/ReLA/assets/71909976/fc902b83-76f3-4f62-a860-60fc01182444)

**Comment by yahooo-m** [comment]
The same results！

**Comment by henghuiding** [comment]
Hi, thank you for raising this issue.  

The results are correct. It is expected that the performance of the released models is slightly better than that reported in our CVPR paper. We have optimized the model after the submission of the camera-ready version, for example [here](https://github.com/henghuiding/ReLA/blob/main/gres_model/modeling/transformer_decoder/referring_transformer_decoder.py#L446). For the original version please kindly refer to this [branch](https://github.com/henghuiding/ReLA/tree/original).

**Comment by qiulesun** [comment]
@henghuiding 

When I reproduce your results using gres_r50.pth model, I encounter the following problem.  Could you provide some suggestions to fix it ?

inference cmd：
 python train_net.py \
    --config-file configs/referring_R50.yaml \
    --num-gpus 2 --dist-url auto --eval-only \
    MODEL.WEIGHTS modes/gres_r50.pth \
    OUTPUT_DIR modes/gres_r50-eval

![image](https://github.com/henghuiding/ReLA/assets/17628841/71978526-453e-4c91-886c-6728d5619ebb)

**Comment by ntuLC** [comment]
Hi,

This issue is likely to be caused by running out of CPU RAM. Try closing other running programs and retry.

Best,
Liu
________________________________

**Comment by qiulesun** [comment]
@ntuLC 

My CPU RAM is 64GB and I already close all programs when running released code.
But whether I fine-tune model or use released model to reproduce the results, there's always this problem. I have no idea to fix it. Can you give me some suggestions ?

![abcb1ae05fa567835ce6677ae742431a_256561193-71978526-453e-4c91-886c-6728d5619ebb](https://github.com/henghuiding/ReLA/assets/17628841/b519c81c-b3fb-48f6-b0af-d52ed5666cee)

**Comment by ntuLC** [comment]
> @ntuLC @henghuiding
> 
> My CPU RAM is 64GB and I already close all programs when running released code. But whether I fine-tune model or use released model to reproduce the results, there's always this problem. I have no idea to fix it. Can you give me some suggestions ?
> 
> ![abcb1ae05fa567835ce6677ae742431a_256561193-71978526-453e-4c91-886c-6728d5619ebb](https://user-images.githubusercontent.com/17628841/269471807-b519c81c-b3fb-48f6-b0af-d52ed5666cee.png)

Hi @qiulesun ,

You may monitor the system memory usage using `top` whilst running, or check your system log to confirm whether it is an OOM issue.

**Comment by Yeemkt** [comment]
> I performe the given Inference code but get the different evaluation result from that in the paper: My gIoU is 66.3407, cIoU is 63.0991, but in the paper they are respectively 63.60 and 62.42
> 
> Here follow my running code, file directory and the output. Is there anything wrong? Thank you.
> 
> !python train_net.py --config-file configs/referring_swin_base.yaml --num-gpus 1 --dist-url auto --eval-only MODEL.WEIGHTS "/content/ReLA/gres_swin_base.pth" OUTPUT_DIR "/content/ReLA" ![image](https://private-user-images.githubusercontent.com/71909976/252691531-fc902b83-76f3-4f62-a860-60fc01182444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MTg5OTYsIm5iZiI6MTcwMjgxODY5NiwicGF0aCI6Ii83MTkwOTk3Ni8yNTI2OTE1MzEtZmM5MDJiODMtNzZmMy00ZjYyLWE4NjAtNjBmYzAxMTgyNDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDEzMTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmODM3NjdmYjJiNDUwZWQ5MWVmMmE0OWVlMDlkM2NiNzg4NzFmOThlMzM2ODg5MjFjZWRjMjc1NDgzODJjYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ImKl7_n0fLuIGHu9eJQhkwj7zHc1sPhUTSkTNvEFU5k)

hi ,can you provide the environment to reproduce .
i want to know the version of cuda and torch
when i run the cmd, it turns out "Segmentation fault"

**Comment by lcl-git-3d** [comment]
![image](https://github.com/henghuiding/ReLA/assets/125371176/0a66210b-18ed-4432-9bea-41c9e78f33db)
Hello! Why my evaluation result is not same with you? @qiulesun
