### ISSUE TITLE
model

### ISSUE THREAD

**Issue by wxqlab** [henghuiding/ReLA#11]
Hi~
what is the "MODEL.WEIGHTS" in the training process?

**Comment by ntuLC** [comment]
Hi Siten,

That should be the converted backbone weights (swin_base_patch4_window12_384_22k.pkl). Please refer to the training section in README.md.
________________________________
From: Siten ***@***.***>
Sent: Monday, July 17, 2023 10:39:57 AM
To: henghuiding/ReLA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [henghuiding/ReLA] model (Issue #11)


Hi~
what is the "MODEL.WEIGHTS" in the training process?

**Comment by wxqlab** [comment]
@ntuLC 
Hi~Thank you very much, I will read the "README.md" carefully again.
