### ISSUE TITLE
Request for Demo: Performing GRES Tasks on Single Images and Text Descriptions

### ISSUE THREAD

**Issue by FantasticGu** [henghuiding/ReLA#4]
Thank you for the excellent work done by the author! 

May I kindly request if it is possible to provide a demo that can perform GRES tasks on input single images and text descriptions?

**Comment by henghuiding** [comment]
That's a really good suggestion! We will try it asap, if feasible and resource availability permits. Thank you.

**Comment by YoLandy** [comment]
Why is the issue closed? If I understand the code correctly, then in GRES.forward() you need to put dictionaries with fields 'image', 'lang_token', 'lang_mask',
'instances',
If the first is intuitively clear, then questions arise with the rest ...

The neural network looks really cool!
