### ISSUE TITLE
About Batch_Size.

### ISSUE THREAD

**Issue by YRlin-12** [henghuiding/ReLA#5]
According to your supplementary file, the model is trained for 150,000 iterations with a batch size of 24 on four 32G V100 GPUs.
Do you mean the IMG_PER_BATCH is 24 or IMG_PER_BATCH is 6, and the total BS is 24?

Thanks.

**Comment by ntuLC** [comment]
Hi,

Please note that we have further fine-tuned some hyperparameters for better performance. The current checkpoint was trained using the default configuration files mentioned in the README. Thank you for your reminder, and we have added this information to the documentation. 

For customized training, the value of SOLVER.IMS_PER_BATCH should be set as the total batch size across all GPUs (e.g., 48 for 6 samples * 8 GPUs).
