### ISSUE TITLE
About the training time

### ISSUE THREAD

**Issue by Nastu-Ho** [henghuiding/ReLA#6]
According to your supplementary file, the model is trained for 150,000 iterations with a batch size of 24 on four 32G V100 GPUs.
How long does it take to complete a training?

**Comment by ntuLC** [comment]
Hi,

Please note that we have further fine-tuned some hyperparameters for better performance. The current checkpoint was trained using the default configuration files mentioned in the README. Thank you for your reminder, and we have added this information to the documentation. For training with 8 GPUs and a batch size of 48, it typically takes about 3-4 days for 30k iterations.

**Comment by henghuiding** [comment]
We provide results based on resource-friendly ResNet-50 and Swin-Tiny backbones. Please kindly also consider reporting results on these small backbones as an alternative choice.

**Comment by PanXiongAdam** [comment]
> Please note that we have further fine-tuned some hyperparameters for better performance. The current checkpoint was trained using the default configuration files mentioned in the README. Thank you for your reminder, and we have added this information to the documentation. For training with 8 GPUs and a batch size of 48, it typically takes about 3-4 days for 30k iterations.

Hello! you said that using the current performance configuration would result in better performance. Can you add the current performance indicators to readme.md? What I see is still the indicator in the article about swin-base.
