### ISSUE TITLE
Qualitative or Qualitative comparison with Grounded SAM

### ISSUE THREAD

**Issue by DarrenIm** [henghuiding/ReLA#7]
Awesome works!
Just ask out of curiosity, did you guys do any comparison with [Grounded-SAM](https://github.com/IDEA-Research/Grounded-Segment-Anything)? Seems like these two works are somewhat similar.

**Comment by ntuLC** [comment]
Hi,

Thank you for your attention! Since Grounded-SAM is a very recent work, we were unable to include a comparison with it in our conference paper. However, we appreciate the suggestion and will certainly consider incorporating more recent works in future.
