### ISSUE TITLE
Question on data split

### ISSUE THREAD

**Issue by RunDevil-Run** [henghuiding/ReLA#9]
I notice grefs(unc).json only contains 18495 images, which is different from 19994 in the paper, and maybe testA/B are not included in this json file? Thank you.

**Comment by henghuiding** [comment]
Thank you for your attention. Yes, the remaining are test A/B, which are not included in the "grefs(unc).json" file. These test sets will be made available on CodaLab for online evaluation and competition. We will notify you once the CodaLab evaluation is ready. Appreciate your understanding.
